// Font Awesome Icons library for category selection
export const faIconsLibrary = [
    { name: "GiPoloShirt", label: "Shirt" },
    { name: "FaTshirt", label: "T-Shirt" },
    { name: "GiTShirt", label: "Tee Shirt" },
    { name: "GiTrousers", label: "Pants" },
    { name: "GiArmoredPants", label: "Cargo Pants" },
    { name: "GiShorts", label: "Shorts" },
    { name: "GiAmpleDress", label: "Dress" },
    { name: "GiClothes", label: "Clothes" },
    { name: "GiSleevelessJacket", label: "Jacket" },
    { name: "GiLargeDress", label: "Gown" },
    { name: "GiMonclerJacket", label: "Outerwear" },
    { name: "GiRunningShoe", label: "Shoes" },
    { name: "FaShoePrints", label: "Footwear" },
    { name: "FaUserTie", label: "Formal Wear" },
    { name: "GiConverseShoe", label: "Sneakers" },
    { name: "GiBallerinaShoes", label: "Heels" },
    { name: "FaHatCowboy", label: "Hat" },
    { name: "GiBilledCap", label: "Cap" },
    { name: "GiSunglasses", label: "Sunglasses" },
    { name: "GiWatch", label: "Watch" },
    { name: "GiBelt", label: "Belt" },
    { name: "GiShoulderBag", label: "Handbag" },
    { name: "GiAmpleDress", label: "Women" },
    { name: "FaMale", label: "Men" },
    { name: "FaFemale", label: "Women Fashion" },
    { name: "GiRolledCloth", label: "Fabric" },
    { name: "GiSewingNeedle", label: "Tailoring" },
    { name: "GiHanger", label: "Wardrobe" },
    { name: "FaStore", label: "Store" },
    { name: "FaShoppingBag", label: "Shopping Bag" },
    { name: "FaGift", label: "Gift" },
    { name: "FaGem", label: "Diamond" },
    { name: "FaRing", label: "Ring" },
    { name: "FaLink", label: "Necklace" },
    { name: "FaLink", label: "Bracelet" },
    { name: "FaGlobe", label: "Earth" },
    { name: "FaClock", label: "Clock" },
    { name: "FaTint", label: "Droplet" },
    { name: "FaPalette", label: "Palette" },
    { name: "FaBrush", label: "Brush" },
    { name: "FaPen", label: "Pen" },
    { name: "FaHeart", label: "Heart" },
    { name: "FaHandsHelping", label: "Hand Holding Heart" },
    { name: "FaStar", label: "Star" },
    { name: "FaStars", label: "Sparkles" },
    { name: "FaStarOfLife", label: "Glitter" },
    { name: "FaFire", label: "Fire" },
    { name: "FaMagic", label: "Magic Wand" },
    { name: "FaCircle", label: "Circle" },
    { name: "FaBook", label: "Book" },
    { name: "FaTag", label: "Tag" },
    { name: "FaBox", label: "Box" },
    { name: "FaLayerGroup", label: "Layer Group" },
    { name: "FaLightbulb", label: "Lightbulb" },
    { name: "FaKey", label: "Key" },
    { name: "FaLock", label: "Lock" },
    { name: "FaGem", label: "Gem" },
    { name: "FaCrown", label: "Crown" },
    { name: "FaFeather", label: "Feather" },
    { name: "FaLeaf", label: "Leaf" },
    { name: "FaLeaf", label: "Flower" },
    { name: "FaWind", label: "Sky" },
    { name: "FaSun", label: "Sun" },
    { name: "FaMoon", label: "Moon" },
    { name: "FaSnowflake", label: "Snowflake" },
    { name: "FaArrowRight", label: "Arrow Right" },
    { name: "FaArrowLeft", label: "Arrow Left" },
    { name: "FaArrowUp", label: "Arrow Up" },
    { name: "FaArrowDown", label: "Arrow Down" },
    { name: "FaImage", label: "Artwork" },
    { name: "FaSquare", label: "Canvas" },
    { name: "FaMask", label: "Mask" },
    { name: "FaTheaterMasks", label: "Theatre Masks" },
    { name: "FaMusic", label: "Music" },
    { name: "FaBell", label: "Bell" },
    { name: "FaAsterisk", label: "Asterisk" },
    { name: "FaAsterisk", label: "Hexagon" },
    { name: "FaDotCircle", label: "Dot Mandalas" },
    { name: "FaSpinner", label: "Mandalas" },
    { name: "FaKey", label: "Keychains" },
    { name: "FaIdCard", label: "Name Plate" },
];

export const getIconByName = (iconName: string): any => {
    // This function will be used client-side to dynamically import the icon
    // The actual icon component needs to be imported from react-icons/fa
    return iconName;
};
